-- Migration for an EXISTING `kbo` database created before pick_mstr.algorithm_code existed.
-- Apply by hand (no Flyway/Liquibase). Fresh databases should use schema.sql instead.

ALTER TABLE kbo.pick_mstr
    ADD COLUMN algorithm_code VARCHAR(30) NULL AFTER user_name,
    ADD KEY idx_pick_mstr_algo_ymd (algorithm_code, ymd);

-- Backfill: every pre-existing simulation pick (user NSC) was generated by the
-- win-rate/odds strategy, now registered as algorithm code 'WIN_RATE_ODDS'.
UPDATE kbo.pick_mstr
   SET algorithm_code = 'WIN_RATE_ODDS'
 WHERE user_name = 'NSC'
   AND algorithm_code IS NULL;
